FROM python:3.10-slim-bullseye as builder

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y curl --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt

COPY . . 

FROM builder as api

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

FROM builder as worker

ENV PYTHONPATH=/app:$PYTHONPATH
CMD ["python", "-m", "app.worker.worker"]